### ISSUE TITLE
mac 快捷键

### ISSUE THREAD

**Issue by heidsoft** [heidsoft/HeidBook#17]
开发者工具：option＋command＋i
javascript控制台：option＋command＋j
或者按option＋command＋c也可以打开

**Comment by heidsoft** [comment]
# mac 安装minikube 报错处理
```
➜  ~ brew cask install minikube
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://storage.googleapis.com/minikube/releases/v0.34.1/minik
Already downloaded: /Users/heidsoft/Library/Caches/Homebrew/downloads/23ed8be8d115c5134e05d15860bc70181672e7a41c45eb878d71b8d479df3a53--minikube-darwin-amd64
==> Verifying SHA-256 checksum for Cask 'minikube'.
==> Installing Cask minikube
==> Linking Binary 'minikube-darwin-amd64' to '/usr/local/bin/minikube'.
==> Purging files for version 0.34.1 of Cask minikube
Error: Failure while executing; `/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames \(\"minikube\"\) /usr/local/Caskroom/minikube/0.34.1/minikube-darwin-amd64` exited with 1. Here's the output:
  File "/usr/bin/xattr", line 31
    continue
           ^
TabError: inconsistent use of tabs and spaces in indentation


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/relocated.rb:73:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:65:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:52:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:200:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

## 解决办法
```
➜  ~ cp  /usr/bin/xattr /usr/bin/xattr.bak
cp: /usr/bin/xattr.bak: Permission denied
➜  ~ sudo cp  /usr/bin/xattr /usr/bin/xattr.bak
➜  ~ cp /usr/bin/xattr-2.7 /usr/bin/xattr
cp: /usr/bin/xattr: Permission denied
➜  ~ sudo cp /usr/bin/xattr-2.7 /usr/bin/xattr
➜  ~ cd
➜  ~ brew cask install minikube
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://storage.googleapis.com/minikube/releases/v0.34.1/minik
Already downloaded: /Users/heidsoft/Library/Caches/Homebrew/downloads/23ed8be8d115c5134e05d15860bc70181672e7a41c45eb878d71b8d479df3a53--minikube-darwin-amd64
==> Verifying SHA-256 checksum for Cask 'minikube'.
==> Installing Cask minikube
==> Linking Binary 'minikube-darwin-amd64' to '/usr/local/bin/minikube'.
🍺  minikube was successfully installed!
➜  ~
```
